<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UsersDevSeeder extends Seeder
{
	public function run()
	{
		$data = [
			[
				'name' => 'Anahi Block',
				'email' => 'Rice@app.com',
				'bio' => 'Similique dolorem asperiores unde non nisi ipsa eum non. Ipsum quo natus dolore saepe. Eligendi qui iure nam veritatis qui provident est.',
				'username' => 'esse',
				'password' => 'deposit',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Linda Quitzon',
				'email' => 'Borer@app.com',
				'bio' => 'Et ut delectus tenetur. Occaecati vel qui dolore molestiae laudantium sit officiis. Dolores natus minus saepe praesentium dignissimos expedita nesciunt.',
				'username' => 'sit',
				'password' => 'indigo',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Dr. Madeline Hane',
				'email' => 'Price@app.com',
				'bio' => 'Enim et excepturi. Consequatur a ut eum aut. Deleniti deserunt et fuga nulla quo distinctio. Et assumenda dolores aliquam voluptas ducimus ad nesciunt illum rerum.',
				'username' => 'quia',
				'password' => 'open-source',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Mohammed Adams',
				'email' => 'Pouros@app.com',
				'bio' => 'Voluptatem corporis eum quasi. Molestiae molestias magni quaerat iste atque totam et. Harum distinctio qui impedit et in natus ut. Maiores id repellat quia quia exercitationem in quas aut aut. Itaque sapiente neque nulla corrupti temporibus nihil corrupti ut.',
				'username' => 'nesciunt',
				'password' => 'Health',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Verla Hirthe II',
				'email' => 'Hudson@app.com',
				'bio' => 'Quas itaque commodi et amet corrupti blanditiis. Similique et incidunt placeat aliquam fugit. Inventore suscipit placeat.',
				'username' => 'et',
				'password' => 'Quality',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Devin Swift',
				'email' => 'Schuppe@app.com',
				'bio' => 'Inventore voluptatem ratione laudantium et. Vel ad temporibus quos dolores error vel. Quod officia reprehenderit voluptate qui. Impedit voluptas veritatis velit ut minus et distinctio. Vel est et commodi quos.',
				'username' => 'vero',
				'password' => 'Unbranded',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Amos McCullough',
				'email' => 'Pouros@app.com',
				'bio' => 'Ut est et facilis ducimus molestias quibusdam. Et quo eius adipisci qui. Sapiente enim quis veniam. Et repellendus autem voluptatem eaque voluptates dolore. Libero provident et dolores ipsam similique sunt ratione. Consequuntur nihil sed quo minus molestias perferendis.',
				'username' => 'soluta',
				'password' => 'functionalities',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Maddison Fahey',
				'email' => 'Kunde@app.com',
				'bio' => 'Non sit tempora recusandae cumque esse consequatur soluta earum amet. In tenetur pariatur soluta dolorem optio ut veniam sequi est. Itaque sunt voluptatem consequatur veritatis et doloremque beatae quaerat mollitia.',
				'username' => 'et',
				'password' => 'Multi-tiered',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Dorothy King',
				'email' => 'Wuckert@app.com',
				'bio' => 'Sunt sit quo qui at. Placeat consequatur architecto incidunt. Ab veritatis officiis qui nihil id ullam. Dolores beatae quisquam est nam.',
				'username' => 'enim',
				'password' => 'Central',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Glenna Stoltenberg',
				'email' => 'Hessel@app.com',
				'bio' => 'Itaque omnis assumenda et. Quia adipisci enim culpa id illum dolorem voluptatem molestiae error. Fuga voluptates modi aut dolor sunt tenetur.',
				'username' => 'impedit',
				'password' => 'Bedfordshire',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Randall Skiles',
				'email' => 'Pacocha@app.com',
				'bio' => 'Aut at facilis quas dignissimos dolorem ut ut architecto. Molestiae beatae minima omnis eos ea modi doloremque id. Quas inventore commodi. Velit minima assumenda.',
				'username' => 'occaecati',
				'password' => 'hacking',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Mr. Justen Willms',
				'email' => 'Ankunding@app.com',
				'bio' => 'Magnam inventore velit dolor omnis accusantium itaque doloremque quas eligendi. Explicabo necessitatibus ratione. Placeat voluptatem sed numquam earum explicabo similique.',
				'username' => 'eius',
				'password' => 'Savings Account',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Bennett Gorczany',
				'email' => 'Botsford@app.com',
				'bio' => 'Vero veniam totam sed omnis qui optio occaecati dolores. Omnis voluptates nostrum vel et illo molestiae hic. Sequi quaerat adipisci molestiae maxime eum quam. Qui aliquam sapiente assumenda.',
				'username' => 'at',
				'password' => 'Granite',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Millie Johnston',
				'email' => 'Emard@app.com',
				'bio' => 'Inventore laborum est voluptatem. Beatae totam incidunt possimus non temporibus.',
				'username' => 'architecto',
				'password' => 'Response',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Miss Jennie Blanda',
				'email' => 'Rosenbaum@app.com',
				'bio' => 'Tempore debitis ipsum autem magnam nemo voluptatem. Sed et et ad sed corrupti et est. Id temporibus voluptas harum hic voluptas labore. Est nobis quis non est quia.',
				'username' => 'officia',
				'password' => 'orchestrate',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Cloyd Mitchell DDS',
				'email' => 'Hegmann@app.com',
				'bio' => 'Iusto dolor laudantium molestias. Qui inventore voluptatem. Et ab illo et quia commodi et debitis. Impedit omnis velit quia et veritatis sed. Commodi et in facilis corrupti ut necessitatibus praesentium dignissimos dolore.',
				'username' => 'magni',
				'password' => 'Clothing',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Miss Darrell Yost',
				'email' => 'King@app.com',
				'bio' => 'Officia enim officia porro dolores necessitatibus sint. Aspernatur ut dolores aperiam porro omnis voluptate. Possimus sed ut doloribus sed. Sit accusamus facere est vero pariatur voluptatem error adipisci.',
				'username' => 'necessitatibus',
				'password' => 'Handcrafted',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Vito Pagac',
				'email' => 'Greenholt@app.com',
				'bio' => 'Sed voluptatibus aut ut. In placeat saepe iure nesciunt porro.',
				'username' => 'voluptates',
				'password' => 'Mount',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Jairo Pacocha',
				'email' => 'Durgan@app.com',
				'bio' => 'Asperiores quod et. Id fugiat et dolore corporis nulla laudantium. Sapiente at numquam enim at quos rem doloribus. Commodi pariatur cumque quidem dolorem voluptatem dolore. Velit quia labore sed dolores.',
				'username' => 'rem',
				'password' => 'Texas',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Naomie Cormier',
				'email' => 'Crooks@app.com',
				'bio' => 'Repellat accusamus nemo molestiae quibusdam et rerum minus excepturi necessitatibus. Neque sint optio qui et aspernatur. Sed consectetur doloribus tempora esse autem sit ducimus.',
				'username' => 'dolore',
				'password' => 'orange',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			],
			[
				'name' => 'Rosina Dibbert',
				'email' => 'Huel@app.com',
				'bio' => 'Ipsum quos inventore eligendi dolore esse. Non dolor itaque voluptatem. Iusto non omnis nemo. Eum id et laboriosam dolore et est.',
				'username' => 'voluptatibus',
				'password' => 'Brand',
				'role' => '1',
				'last_login' => date("Y-m-d H:i:s"),
				'created_at' => date('Y-m-d H:i:s'),
			]
		];

		foreach ($data as $value) {
			$this->db->table('users')->insert($value);
		}
	}
}
